### ISSUE TITLE
1.0.2 throw error

### ISSUE THREAD

**Issue by vr6syncro** [CorantGmbH/ioBroker.air-q#65]
Updated to 1.0.2 and got many errors. deleated object table and restart adapter but did not help.

```
<html>
<body>
<!--StartFragment-->
air-q.0 | 2024-05-03 19:49:40.297 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
air-q.0 | 2024-05-03 19:49:40.296 | info | terminating
air-q.0 | 2024-05-03 19:49:39.796 | info | AirQ adapter stopped...
air-q.0 | 2024-05-03 19:49:39.795 | error | this.sensorArray is not iterable
air-q.0 | 2024-05-03 19:49:39.795 | error | TypeError: this.sensorArray is not iterable at AirQ.onReady (/opt/iobroker/node_modules/iobroker.air-q/build/main.js:79:34) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
air-q.0 | 2024-05-03 19:49:39.794 | error | unhandled promise rejection: this.sensorArray is not iterable
air-q.0 | 2024-05-03 19:49:39.794 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
air-q.0 | 2024-05-03 19:49:39.793 | error | Error while getting sensors from device: Error: DecryptedData is undefined or not an object
air-q.0 | 2024-05-03 19:49:39.796 | info | AirQ adapter stopped...
air-q.0 | 2024-05-03 19:49:39.795 | error | this.sensorArray is not iterable
air-q.0 | 2024-05-03 19:49:39.795 | error | TypeError: this.sensorArray is not iterable at AirQ.onReady (/opt/iobroker/node_modules/iobroker.air-q/build/main.js:79:34) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
air-q.0 | 2024-05-03 19:49:39.794 | error | unhandled promise rejection: this.sensorArray is not iterable
air-q.0 | 2024-05-03 19:49:39.794 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
air-q.0 | 2024-05-03 19:49:39.793 | error | Error while getting sensors from device: Error: DecryptedData is undefined or not an object
air-q.0 | 2024-05-03 19:49:39.027 | error | Error: DecryptedData is undefined or not an object
air-q.0 | 2024-05-03 19:49:38.362 | info | starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.air-q, node: v18.20.1, js-controller: 5.0.12

<!--EndFragment-->
</body>
</html>
```

**Comment by mario-airq** [comment]
thanks for your feedback @vr6syncro . we will check this.

**Comment by pr0crstntr** [comment]
hey! it seems like the adapter has issues with decrypting the data it's getting from the device. could you give us some more information on which device you're using or which sensors it includes? :) @vr6syncro

**Comment by pr0crstntr** [comment]
also make sure that the password and ip/id are correct. I could recreate the errors when i misspelled my password

**Comment by vr6syncro** [comment]
hi, reentering the password seems to fix the issue. never changed it... I could have figured it out myself, but I didn't think about it when I received this error message.  Thanks.


```
<html>
<body>
<!--StartFragment-->
air-q.0 | 2024-05-08 16:49:41.974 | info | starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.air-q, node: v18.20.1, js-controller: 5.0.12
-- | -- | -- | --
air-q.0 | 2024-05-08 16:49:39.910 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
air-q.0 | 2024-05-08 16:49:39.910 | info | terminating

<!--EndFragment-->
</body>
</html>
```


maybe you can add a messege if the login is sucessfull and if the data is received. im on debug/silly but dont get any infos from the adapter.
